services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
      - ./shared:/shared
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=sqlite+aiosqlite:///./sql_app.db
    restart: always

networks:
  default:
    name: idepocket-network
